# Numpy
---
- numpy : numerical python
- ndarray라는 고성능 다차월 배열 객체와 이를 다루는 여러 함수를 제공한다. 


In [1]:
#배열 생성
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
#배열 정보보기
print(type(a))

#배열의 차원
print(a.ndim)

#배열의 크기
print(a.shape)

#원소 자료형
print(a.dtype)

<class 'numpy.ndarray'>
2
(2, 2)
int64


In [5]:
#배열의 접근
print(a[0], a[1])

[1 2] [3 4]


In [7]:
print(a[0][0], a[0][1])
print(a[1][0], a[1][1])

1 2
3 4


In [12]:
#배열 형태 바꾸기
#a.T는 transpose 이다. a.transpose() 를 사용해도 같은 결과를 가진다.
print(a, end = '\n\n')
print(a.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [20]:
#flatten은 다차원 배열을 1차원 배열 형태로 바꾸는데 사용하며, 평탄화라고 한다. 
print(a, end = '\n\n')
print(a.flatten())
print('차원의 형태는',a.flatten().shape)

[[1 2]
 [3 4]]

[1 2 3 4]
차원의 형태는 (4,)


In [22]:
#배열의 연산
#사칙연산이 다 되지만 곱셈이랑 나눗셈은 각 배열의 위치 값들끼리 곱하고 나눈다. 
#차원이 다른 행렬끼리도 사칙연산이 가능하고 이를 브로드캐스팅이라고 한다. 
#아래의 경우 각 행별로 10,100 행렬이 곱해진 것을 볼 수 있다. 
b = np.array([10,100])
a * b

array([[ 10, 200],
       [ 30, 400]])

In [24]:
#내적 구하기
#10 * 10 + 100 * 100
b.dot(b)

10100

In [26]:
# 1 * 10 + 2 * 100
# 3 * 10 + 4 * 100
a.dot(b)

array([210, 430])

# Pandas
---
- 판다스는 금융 데이터 분석을 목적으로 개발되었으며 구조화된 데이터를 쉽고 빠르게 가공할 수 있는 자료형과 함수를 제공한다. 
- 판다스의 이름은 panel data, python data analysis 에서 유래했다. 
- 넘파이를 기반으로 구현했기 때문에 유사하다. 

In [1]:
# 시리즈 생성
import pandas as pd
s= pd.Series([0.0,3.6,2.0,5.8,4.2,8.0])
s

0    0.0
1    3.6
2    2.0
3    5.8
4    4.2
5    8.0
dtype: float64

In [28]:
# 시리즈의 인덱스 변경
# 인덱스의 값도 변경이 가능하고 이름도 설정이 가능하다. 
s.index = pd.Index([.0,1.2,1.8,3.0,3.6,4.8])
s.index.name = 'MY_IDX'
s

MY_IDX
0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
dtype: float64

In [29]:
# 시리즈의 이름을 설정할 수 있다. 
s.name = 'MY_SERIES'
s

MY_IDX
0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
Name: MY_SERIES, dtype: float64

In [32]:
#데이터 추가
#새로운 인덱스에 새로운 값을 넣으면 추가되는 것을 볼 수 있다. 
s[5.9] = 5.5
s

MY_IDX
0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
5.9    5.5
Name: MY_SERIES, dtype: float64

In [34]:
#append 함수를 사용해서 기존의 시리즈에 값을 추가할 수 있다.
ser = pd.Series([6.7,4.2], index = [6.8,8.0])
s = s.append(ser)
s

0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
5.9    5.5
6.8    6.7
8.0    4.2
6.8    6.7
8.0    4.2
dtype: float64

In [41]:
#데이터 인덱싱
print(s.index[-1])
print(s.values[-1])
#print(s.loc[8.0])
print(s.iloc[-1])
print(s.values[:])

8.0
4.2
4.2
[0.  3.6 2.  5.8 4.2 8.  5.5 6.7 4.2 6.7 4.2]


In [42]:
#데이터 삭제
s.drop(8.0)

0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
5.9    5.5
6.8    6.7
6.8    6.7
dtype: float64

In [2]:
#시리즈 출력하기
import matplotlib.pyplot as plt
plt.title('ELLIOTT_WAVE')
plt.plot(s, 'bs--')
plt.xticks(s.index)
plt.yticks(s.values)
plt.grid(True)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'